// stack1/frontend/journal-angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {AccountService} from '../services/AccountService';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  public username: string;
  public password: string;

  constructor(private accService: AccountService) { }

  ngOnInit() {
  }

  onSubmit() {
    console.log('login clicked');

    this.accService.authenticate(this.username, this.password).subscribe(response => {
      console.log('Response: ', response);
    });
  }

}


  <form (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="username_login_input">Användarnamn: </label>
      <input type="text" name="username" id="username_login_input" class="form-control" [(ngModel)]="username">
    </div>
    <div class="form-group">
      <label for="password_login_input">Lösenord: </label>
      <input type="password" name="password" id="password_login_input" class="form-control" [(ngModel)]="password">
    </div>

    <button type="submit" class="btn btn-primary">Logga in</button>
  </form>

// stack2/frontend/journal-react/src/Login.js
import React, { Component } from 'react';
import AccountService from "./services/AccountService";

export default class Login extends Component {

	constructor(props) {
		super(props);
		this.state = {
			username: '',
			password: ''
		};
		this.loginSubmit    = this.loginSubmit.bind(this);
		this.usernameChange = this.usernameChange.bind(this);
		this.passwordChange = this.passwordChange.bind(this);
	}

	loginSubmit(e){
		e.preventDefault();
		let username = this.state.username;
		let password = this.state.password;
		AccountService.login(username, password)
			.then(() => {
				this.props.history.push('/home');
			});
	}

	componentDidMount() {
		if(AccountService.getApiKey() !== null) {
			this.props.history.replace('/home');
		}
	}

	usernameChange(e){
		this.setState({
			username: e.target.value
		});
	}

	passwordChange(e){
		this.setState({
			password: e.target.value
		});
	}

	render(){
		let headerStyle = {textAlign: 'center'};

		return (
			<div className="col-md-6 col-md-offset-3">
				<h2 style={headerStyle}>Welcome to Journaling</h2>
				<form onSubmit={this.loginSubmit}>
					<div className="form-group">
						<label htmlFor="login_form_username_input">Användarnamn: </label>
						<input type="text" className="form-control" id="login_form_username_input" value={this.state.username} onChange={this.usernameChange}/>
					</div>
					<div>
						<label htmlFor="login_form_password_input">Användarnamn: </label>
						<input type="password" className="form-control" id="login_form_password_input" value={this.state.password} onChange={this.passwordChange}/>
					</div>
					<br/>
					<button type="submit" className="btn btn-success">Logga in</button>
				</form>
			</div>
		);
	}

}
